<?xml version="1.0"?>

<robot name="base" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Define a number of dimensions using properties -->
  <xacro:property name="base_size_x" value="0.22" />
  <xacro:property name="base_size_y" value="0.16" />
  <xacro:property name="base_size_z" value="0.052" />
  
  <xacro:property name="wheel_length" value="0.01" />
  <xacro:property name="wheel_radius" value="0.044" />
  <xacro:property name="wheel_offset_x" value="0.062" />
  <xacro:property name="wheel_offset_y" value="0.095" />
  <xacro:property name="wheel_offset_z" value="-0.044" />
  
  <xacro:property name="caster_radius" value="0.0125" />
  <xacro:property name="caster_offset_x" value="-0.09" />
  <xacro:property name="caster_offset_y" value="0.0" />
  <xacro:property name="caster_offset_z" value="-0.076" />
  
  <xacro:property name="PI" value="3.1415" />
  
  <xacro:macro name="box_inertia" params="m x y z">
      <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
      iyy="${m*(x*x+z*z)/12}" iyz = "0"
      izz="${m*(x*x+z*z)/12}" /> 
  </xacro:macro>

  <!-- The base xacro macro -->
  <xacro:macro name="base" params="name color">
  
     <link name="base_footprint" />
     <joint name="base_footprint_joint" type="fixed">
         <origin xyz="0 0 0" rpy="0 0 0" />
         <parent link="base_footprint" />
         <child link="base_link" />
     </joint>
     
     <!-- Base link is the center of the robot's chassis between the motors projected on the ground -->
     <link name="base_link"/>

     <joint name="base_chassis_joint" type="fixed">
         <origin xyz="0 0 0" rpy="0 0 0" />
         <parent link="base_link" />
         <child link="base_chassis_link" />
     </joint>
        
     <gazebo reference="base_chassis_link">
        <material>Gazebo/Black</material>
     </gazebo>
    
     <link name="base_chassis_link">
		<inertial>
			<mass value="1.0" />
			<origin xyz="0 0 0" />
			<xacro:box_inertia m="1.0" x="0" y="0" z="0"/>
	    </inertial>
        
        <visual>
           <origin xyz="0 0 0" rpy="0 0 0" />
           <geometry>
              <box size="${base_size_x} ${base_size_y} ${base_size_z}" />
           </geometry>
           <material name="${color}" />
         </visual>
      
         <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
               <box size="${base_size_x} ${wheel_offset_y*2 + wheel_length} ${base_size_z}" />
            </geometry>
         </collision>
     </link>

  </xacro:macro>
  
  <!-- define a wheel -->
  <xacro:macro name="wheel" params="wheel_prefix parent rotation *origin">
		<joint name="${wheel_prefix}_wheel_joint" type="continuous">
			<parent link="${parent}"/>
			<child link="${wheel_prefix}_wheel_link"/>
			<xacro:insert_block name="origin"/>
			<axis xyz="0 1 0" rpy="0 0 0" />
		</joint>

		<link name="${wheel_prefix}_wheel_link">
			<inertial>
				<mass value="0.1" />
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<inertia  ixx="0.00303625" ixy="0.000000" ixz="0.000000"
                          iyx="0.000000" iyy="0.00303625" iyz="0.000000"
                          izx="0.000000" izy="0.000000" izz="0.00578884" />
			</inertial>
			
			<visual>
			    <origin xyz="0 0 0" rpy="${rotation} 0 0"/>
				<geometry>
					<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
				</geometry>
			</visual>
			
			<collision>
			    <origin xyz="0 0 0" rpy="${rotation} 0 0"/>
				<geometry>
					<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
				</geometry>
			</collision>
		</link>

  </xacro:macro>
  
  <!-- define a caster -->
  <xacro:macro name="caster" params="prefix parent color">
    <gazebo reference="${prefix}_caster_link" />
    
    <link name="${prefix}_caster_link">
       <inertial>
          <mass value="0.05" />
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <inertia  ixx="0.01" ixy="0.000000" ixz="0.000000"
                    iyx="0.000000" iyy="0.1" iyz="0.000000"
                    izx="0.000000" izy="0.000000" izz="0.1" />
      </inertial>
      
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <sphere radius="${caster_radius}" />
        </geometry>
        <material name="${color}" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <sphere radius="${caster_radius}" />
        </geometry>
        <material name="${color}" />
        <surface>
           <friction>
              <ode>
                 <mu>0</mu>
                 <mu2>0</mu2>
                 <slip1>1.0</slip1>
                 <slip2>1.0</slip2>
             </ode>
           </friction>
         </surface>
      </collision>
    </link>

    <joint name="${parent}_${prefix}_caster_joint" type="fixed">
      <axis xyz="0 0 1" />
      <origin xyz="${caster_offset_x} ${caster_offset_y} ${caster_offset_z}" rpy="0 0 0" />
      <parent link="${parent}_link"/>
      <child link="${prefix}_caster_link"/>
    </joint>
    
  </xacro:macro>
  
</robot>