<?xml version="1.0"?>

<robot name="sensors" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="sensors">

   <link name="sonar_front_center">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.01 0.03 0.01" />
        </geometry>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.01 0.03 0.01" />
        </geometry>
      </collision>
   </link>
   
   <joint name="sonar_front_center" type="fixed">
      <origin xyz="${base_size_x/2 + 0.01} 0 0" rpy="0 0 0" />
      <parent link="base_link"/>
      <child link="sonar_front_center"/>
    </joint>
    
   <link name="sonar_front_left">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.01 0.03 0.01" />
        </geometry>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.01 0.03 0.01" />
        </geometry>
      </collision>
   </link>
      
   <joint name="sonar_front_left" type="fixed">
      <origin xyz="${base_size_x/2 + 0.01} ${base_size_y/2 - 0.01} 0" rpy="0 0 ${PI/4}" />
      <parent link="base_link"/>
      <child link="sonar_front_left"/>
    </joint>
    
   <link name="sonar_front_right">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.01 0.03 0.01" />
        </geometry>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.01 0.03 0.01" />
        </geometry>
      </collision>
   </link>
   
   <joint name="sonar_front_right" type="fixed">
      <origin xyz="${base_size_x/2 + 0.01} ${-base_size_y/2 + 0.01} 0" rpy="0 0 ${-PI/4}" />
      <parent link="base_link"/>
      <child link="sonar_front_right"/>
    </joint>
    
   <link name="sonar_rear_left">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.01 0.03 0.01" />
        </geometry>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.01 0.03 0.01" />
        </geometry>
      </collision>
   </link>
   
   <joint name="sonar_rear_left" type="fixed">
      <origin xyz="${-base_size_x/2 + 0.01} ${base_size_y/2 + 0.01} 0" rpy="0 0 ${3*PI/4}" />
      <parent link="base_link"/>
      <child link="sonar_rear_left"/>
    </joint>
    
   <link name="sonar_rear_center">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.01 0.03 0.01" />
        </geometry>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.01 0.03 0.01" />
        </geometry>
      </collision>
   </link>
   
   <joint name="sonar_rear_center" type="fixed">
      <origin xyz="${-base_size_x/2 - 0.01} 0 0" rpy="0 0 ${PI}" />
      <parent link="base_link"/>
      <child link="sonar_rear_center"/>
    </joint>
    
   <link name="sonar_rear_right">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.01 0.03 0.01" />
        </geometry>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.01 0.03 0.01" />
        </geometry>
      </collision>
   </link>
   
   <joint name="sonar_rear_right" type="fixed">
      <origin xyz="${-base_size_x/2 + 0.01} ${-base_size_y/2 - 0.01} 0" rpy="0 0 ${-3*PI/4}" />
      <parent link="base_link"/>
      <child link="sonar_rear_right"/>
    </joint>
    
  <link name="ir_front_center">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.01 0.03 0.01" />
        </geometry>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.01 0.03 0.01" />
        </geometry>
      </collision>
   </link>
   
   <joint name="ir_front_center" type="fixed">
      <origin xyz="${base_size_x/2 + 0.01} 0 0" rpy="0 0 0" />
      <parent link="base_link"/>
      <child link="ir_front_center"/>
    </joint>
    
   <gazebo reference="sonar_front_center">
	    <sensor type="ray" name="sonar_front_center_sensor">
	      <pose>0 0 0 0 0 0</pose>
	      <update_rate>5</update_rate>
	      <ray>
	         <scan>
	            <horizontal>
	               <samples>1</samples>
	               <resolution>1.0</resolution>
	               <min_angle>-0.01</min_angle>
	               <max_angle>0.01</max_angle>
	            </horizontal>
	            <vertical>
	               <samples>1</samples>
	               <resolution>1</resolution>
	               <min_angle>-0.01</min_angle>
	               <max_angle>0.01</max_angle>
	            </vertical>
	         </scan>
	         <range>
	            <min>0.01</min>
	            <max>3.75</max>
	            <resolution>0.2</resolution>
	         </range>
	      </ray>
	      
	      <plugin filename="libgazebo_ros_range.so" name="sonar_front_center_plugin">
	         <gaussianNoise>0.1</gaussianNoise>
	         <alwaysOn>true</alwaysOn>
	         <updateRate>5</updateRate>
	         <topicName>/arduino/sensor/sonar_front_center</topicName>
	         <frameName>sonar_front_center</frameName>
	         <visualize>true</visualize>
	         <radiation>sonar</radiation>
	         <fov>0.2</fov>
	      </plugin>
	   </sensor>
   </gazebo>
   
   <gazebo reference="sonar_front_left">
	    <sensor type="ray" name="sonar_front_left_sensor">
	      <pose>0 0 0 0 0 0</pose>
	      <update_rate>5</update_rate>
	      <ray>
	         <scan>
	            <horizontal>
	               <samples>1</samples>
	               <resolution>1.0</resolution>
	               <min_angle>-0.01</min_angle>
	               <max_angle>0.01</max_angle>
	            </horizontal>
	            <vertical>
	               <samples>1</samples>
	               <resolution>1</resolution>
	               <min_angle>-0.01</min_angle>
	               <max_angle>0.01</max_angle>
	            </vertical>
	         </scan>
	         <range>
	            <min>0.01</min>
	            <max>3.75</max>
	            <resolution>0.2</resolution>
	         </range>
	      </ray>
	      
	      <plugin filename="libgazebo_ros_range.so" name="sonar_front_left_plugin">
	         <gaussianNoise>0.1</gaussianNoise>
	         <alwaysOn>true</alwaysOn>
	         <updateRate>5</updateRate>
	         <topicName>/arduino/sensor/sonar_front_left</topicName>
	         <frameName>sonar_front_left</frameName>
	         <visualize>true</visualize>
	         <radiation>sonar</radiation>
	         <fov>0.2</fov>
	      </plugin>
	   </sensor>
   </gazebo>

   <gazebo reference="sonar_front_right">
	    <sensor type="ray" name="sonar_front_right_sensor">
	      <pose>0 0 0 0 0 0</pose>
	      <update_rate>5</update_rate>
	      <ray>
	         <scan>
	            <horizontal>
	               <samples>1</samples>
	               <resolution>1.0</resolution>
	               <min_angle>-0.01</min_angle>
	               <max_angle>0.01</max_angle>
	            </horizontal>
	            <vertical>
	               <samples>1</samples>
	               <resolution>1</resolution>
	               <min_angle>-0.01</min_angle>
	               <max_angle>0.01</max_angle>
	            </vertical>
	         </scan>
	         <range>
	            <min>0.01</min>
	            <max>3.75</max>
	            <resolution>0.2</resolution>
	         </range>
	      </ray>
	      
	      <plugin filename="libgazebo_ros_range.so" name="sonar_front_right_plugin">
	         <gaussianNoise>0.1</gaussianNoise>
	         <alwaysOn>true</alwaysOn>
	         <updateRate>5</updateRate>
	         <topicName>/arduino/sensor/sonar_front_right</topicName>
	         <frameName>sonar_front_right</frameName>
	         <visualize>true</visualize>
	         <radiation>sonar</radiation>
	         <fov>0.2</fov>
	      </plugin>
	   </sensor>
   </gazebo>

  </xacro:macro>

</robot>